Paginate = 4
baseurl = "https://limityjsmemy.github.io/limityjsmemy.cz/"
defaultcontentlanguage = "cs"
theme = "zen"
title = "Limity Jsme My"
[languages.cs]
contentDir = "content/czech"
languageCode = "cs-cz"
languageName = "Česky"
weight = 1
[languages.de]
contentDir = "content/deutsch"
languageName = "Deutsch"
weight = 3
[languages.en]
contentDir = "content/english"
languageName = "English"
weight = 2
[params]
copyright = "This site is licensed under some licence"
dateformat = ""
description = ""
favicon = ""
feedlinks = false
footer = "My jsme limity"
icon = ""
image = ""
imageMaxWidth = ""
jquery = true
languageDir = ""
logo = true
mainSections = ["actions", "posts"]
microUsername = ""
mobileMenu = true
piwikTrackerUrl = ""
poweredby = false
search = true
sidebar = true
submitted = true
