baseurl = "https://matejdivecky.github.io/limityjsmemy.cz/"
title = "LJM"
theme = "zen"

[params]
contact = "info@example.org"
copyright = "This site is licensed under some licence"
dateformat = ""
description = ""
favicon = ""
feedlinks = false
footer = "My jsme limity"
icon = ""
image = ""
imageMaxWidth = ""
jquery = true
languageDir = ""
logo = false
mainSections = [
  "section1",
  "section2"
]
microUsername = ""
mobileMenu = true
piwikTrackerUrl = ""
poweredby = false
search = false
sidebar = true
submitted = true
