Paginate = 4
baseurl = "https://limityjsmemy.github.io/limityjsmemy.cz/"
defaultcontentlanguage = "cs"
theme = "zen"
title = "Limity Jsme My"
[languages.cs]
contentDir = "content/czech"
languageCode = "cs-cz"
languageName = "Česky"
weight = 1
[languages.de]
contentDir = "content/deutsch"
languageCode = "de-de"
languageName = "Deutsch"
weight = 3
[languages.en]
contentDir = "content/english"
languageCode = "en-us"
languageName = "English"
weight = 2
[[menu.header_cs]]
identifier = "join-us"
name = "Přidej se"
url = "/pridej-se"
weight = 2
[[menu.header_cs]]
identifier = "learn-more"
name = "Chci vědět víc"
url = "/o-nas"
weight = 1
[[menu.header_de]]
identifier = "mehr-erfahren"
name = "Mehr erfahren"
url = "/de/ueber-uns"
weight = 1
[[menu.header_de]]
identifier = "mach-mit"
name = "Mach mit"
url = "/de/mach-mit"
weight = 2
[[menu.header_en]]
identifier = "join-us"
name = "Join us"
url = "/en//join-us"
weight = 2
[[menu.header_en]]
identifier = "learn-more"
name = "Learn more"
url = "/en/about-us"
weight = 1
[[menu.main_cs]]
identifier = "pridejse"
name = "Přidej se"
url = "/pridej-se/"
weight = 2
[[menu.main_cs]]
identifier = "onas"
name = "O nás"
url = "/o-nas/"
weight = 1
[[menu.main_de]]
identifier = "macst-du-mit"
name = "Machst du mit!"
url = "/de/machst-du-mit/"
weight = 2
[[menu.main_de]]
identifier = "about"
name = "Über uns"
url = "/de/ueber-uns/"
weight = 1
[[menu.main_en]]
identifier = "get-involved"
name = "Get involved"
pre = "<i class='fa fa-heart'></i>"
url = "/en/get-involved/"
weight = 1
[[menu.main_en]]
identifier = "about"
name = "About us"
pre = "<i class='fa fa-heart'></i>"
url = "/en/about-us/"
weight = 2
[params]
copyright = "This site is licensed under some licence"
dateformat = ""
description = ""
favicon = ""
feedlinks = false
footer = "My jsme limity"
icon = ""
image = ""
imageMaxWidth = ""
jquery = true
languageDir = ""
logo = true
logo_path = "/images/logo.svg"
mainSections = ["actions", "posts"]
microUsername = ""
mobileMenu = true
piwikTrackerUrl = ""
poweredby = false
search = false
sidebar = true
submitted = false
