baseurl = "https://limityjsmemy.github.io/limityjsmemy.cz/"
title = "Limity Jsme My"
theme = "zen"
Paginate = 4

defaultcontentlanguage = "cs"
[languages]
  [languages.en]
    weight = 2
    contentDir = "content/english"
    languageName = "English"
  [languages.cs]
    weight = 1
    contentDir = "content/czech"
    languageName = "Česky"
    languageCode = "cs-cz"
  [languages.de]
    weight = 3
    contentDir = "content/deutsch"
    languageName = "Deutsch"

[params]
    copyright = "This site is licensed under some licence"
    dateformat = ""
    description = ""
    favicon = ""
    feedlinks = false
    footer = "My jsme limity"
    icon = ""
    image = ""
    imageMaxWidth = ""
    jquery = true
    languageDir = ""
    logo = true
    mainSections = [
        "actions",
        "posts"
    ]
    microUsername = ""
    mobileMenu = true
    piwikTrackerUrl = ""
    poweredby = false
    search = false
    sidebar = true
    submitted = true
