Paginate = 4
baseurl = "https://limityjsmemy.github.io/limityjsmemy.cz/"
defaultcontentlanguage = "cs"
theme = "zen"
title = "Limity Jsme My"
[languages.cs]
contentDir = "content/czech"
languageCode = "cs-cz"
languageName = "Česky"
weight = 1
[[languages.cs.menu.main]]
url    = "/"
name   = "Domů"
weight = 0
[languages.de]
contentDir = "content/deutsch"
languageCode = "de-de"
languageName = "Deutsch"
weight = 3
[languages.en]
contentDir = "content/english"
languageCode = "en-us"
languageName = "English"
weight = 2
[[languages.en.menu.main]]
url    = "/"
name   = "Home"
weight = 0
[[menu.main_cs]]
identifier = "about"
name = "about hugo"
pre = "<i class='fa fa-heart'></i>"
url = "/about/"
weight = 1
[[menu.main_de]]
identifier = "about"
name = "about hugo"
pre = "<i class='fa fa-heart'></i>"
url = "/de/about/"
weight = 1
[[menu.main_en]]
identifier = "about"
name = "about hugo"
pre = "<i class='fa fa-heart'></i>"
url = "/en/about/"
weight = 1
[[menu.header_cs]]
identifier = "join-us"
name = "Přidej se"
url = "/pridej-se"
weight = 1
[[menu.header_cs]]
identifier = "learn-more"
name = "Chci vědět víc"
url = "/o-nas"
weight = 1
[[menu.header_en]]
identifier = "join-us"
name = "Join us"
url = "/en//join-us"
weight = 1
[[menu.header_en]]
identifier = "learn-more"
name = "Learn more"
url = "/en/about-us"
weight = 1
[[menu.header_de]]
identifier = "mach-mit"
name = "Mach mit"
url = "/de/mach-mit"
weight = 1
[[menu.header_de]]
identifier = "mehr-erfahren"
name = "Mehr erfahren"
url = "/de/ueber-uns"
weight = 1
[params]
copyright = "This site is licensed under some licence"
dateformat = ""
description = ""
favicon = ""
feedlinks = false
footer = "My jsme limity"
icon = ""
image = ""
imageMaxWidth = ""
jquery = true
languageDir = ""
logo = true
logo_path = "/images/logo.svg"
mainSections = ["actions", "posts"]
microUsername = ""
mobileMenu = true
piwikTrackerUrl = ""
poweredby = false
search = false
sidebar = true
slogan = "Jsme hnutí usilující o ukončení těžby a spalování fosilních paliv.<br>Naším cílem je klimatická spravedlnost."
submitted = false
