baseurl = "https://matejdivecky.github.io/limityjsmemy.cz/"
title = "LJM"
theme = "zen"

[params]
contact = "info@example.org"
copyright = "This site is licensed under some licence"
dateformat = ""
description = ""
favicon = ""
feedlinks = true
footer = "A [example.org](https://example.org/) production."
icon = ""
image = ""
imageMaxWidth = ""
jquery = true
languageDir = ""
logo = false
mainSections = [
  "section1",
  "section2"
]
microUsername = ""
mobileMenu = true
piwikTrackerUrl = ""
poweredby = true
search = true
searchSize = 20.0
sidebar = true
submitted = true
