Paginate = 4
baseurl = "https://limityjsmemy.github.io/limityjsmemy.cz/"
defaultcontentlanguage = "cs"
theme = "zen"
title = "Limity Jsme My"
[languages.cs]
contentDir = "content/czech"
languageCode = "cs-cz"
languageName = "Česky"
weight = 1
[languages.de]
contentDir = "content/deutsch"
languageName = "Deutsch"
weight = 3
[languages.en]
contentDir = "content/english"
languageName = "English"
weight = 2
[params]
copyright = "This site is licensed under some licence"
dateformat = ""
description = ""
favicon = ""
feedlinks = false
footer = "My jsme limity"
icon = ""
image = ""
imageMaxWidth = ""
jquery = true
languageDir = ""
logo = true
mainSections = ["actions", "posts"]
microUsername = ""
mobileMenu = true
piwikTrackerUrl = ""
poweredby = false
search = false
sidebar = true
submitted = true
logo_path = "/images/logo.svg"
slogan = "Jsme hnutí usilující o ukončení těžby a spalování fosilních paliv.<br>Naším cílem je klimatická spravedlnost."
header_action_links = [
    {id = "join-us", text = "Přidej se k nám", url = "/join-us"},
    {id = "learn-more", text = "Chci vědět víc", url = "/o-nas"}
]
social_profiles = [
    {site = "facebook", url = "https://facebook.com", icon_path = "/icons/facebook.svg"},
    {site = "twitter", url = "https://twitter.com", icon_path = "/icons/twitter.svg"}
]
