Paginate = 4
baseurl = "https://limityjsmemy.github.io/limityjsmemy.cz/"
defaultcontentlanguage = "cs"
theme = "zen"
title = "Limity Jsme My"
[languages.cs]
contentDir = "content/czech"
languageCode = "cs-cz"
languageName = "Česky"
weight = 1
[[languages.cs.menu.main]]
url    = "/"
name   = "Úvod"
weight = 0
[languages.de]
contentDir = "content/deutsch"
languageName = "Deutsch"
weight = 3
[[languages.de.menu.main]]
url    = "/"
name   = "Start"
weight = 0
[languages.en]
contentDir = "content/english"
languageName = "English"
weight = 2
[[languages.en.menu.main]]
url    = "/"
name   = "Home"
weight = 0
[params]
copyright = "This site is licensed under some licence"
dateformat = ""
description = ""
favicon = ""
feedlinks = false
footer = "My jsme limity"
icon = ""
image = ""
imageMaxWidth = ""
jquery = true
languageDir = ""
logo = true
logo_path = "/images/logo.svg"
mainSections = ["actions", "posts"]
microUsername = ""
mobileMenu = true
piwikTrackerUrl = ""
poweredby = false
search = false
sidebar = true
slogan = "Jsme hnutí usilující o ukončení těžby a spalování fosilních paliv.<br>Naším cílem je klimatická spravedlnost."
submitted = true
[[params.header_action_links]]
id = "join-us"
text = "Přidej se k nám"
url = "/join-us"
[[params.header_action_links]]
id = "learn-more"
text = "Chci vědět víc"
url = "/o-nas"
[[params.social_profiles]]
icon_path = "/icons/facebook.svg"
site = "facebook"
url = "https://facebook.com"
[[params.social_profiles]]
icon_path = "/icons/twitter.svg"
site = "twitter"
url = "https://twitter.com"
[menu]

  [[menu.main_cs]]
    identifier = "about"
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110
  [[menu.main_en]]
    identifier = "about"
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110
  [[menu.main_de]]
    identifier = "about"
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110
