baseurl = "https://matejdivecky.github.io/limityjsmemy.cz/"
title = "Limity Jsme My"
theme = "zen"

[params]
copyright = "This site is licensed under some licence"
dateformat = ""
description = ""
favicon = ""
feedlinks = false
footer = "My jsme limity"
icon = ""
image = ""
imageMaxWidth = ""
jquery = true
languageDir = ""
logo = true
mainSections = [
  "pages",
  "posts"
]
microUsername = ""
mobileMenu = true
piwikTrackerUrl = ""
poweredby = false
search = false
sidebar = true
submitted = true
DefaultContentLanguage = "cz"
[languages]
  [languages.en]
    weight = 1
    contentDir = "content/english"
    languageName = "English"
  [languages.cz]
    weight = 2
    contentDir = "content/czech"
    languageName = "Česky"
  [languages.de]
    weight = 2
    contentDir = "content/deutsch"
    languageName = "Deutsch"
