---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Czech
- type: directory
  path: content/czech
  label: Pages - CZ
  create: documents
  match: "*"
- type: directory
  path: content/czech/posts/**
  label: Posts - CZ
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/czech/event/**
  label: Event - CZ
  create: all
  match: "**/*"
- type: directory
  path: content/czech/featured/**
  label: Featured - CZ
  create: all
  match: "**/*"
- type: heading
  label: English
- type: directory
  path: content/english
  label: Pages - EN
  create: documents
  match: "*"
- type: directory
  path: content/english/posts
  label: Posts - EN
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/english/event/**
  label: Event - EN
  create: all
  match: "**/*"
- type: directory
  path: content/english/featured/**
  label: Featured - EN
  create: all
  match: "**/*"
upload_dir: content/czech/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.0
